---
- name: install git
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git

- name: get swmp
  git: repo=https://github.com/fuzzymannerz/swmp.git dest={{ swmp.destination }}
